import random

words = [
    "Agali", "Ose", "Obi", "Aka",
    "Oddi", "Otule", "Ogoli", "Okala",
    "Ete", "Akwu", "Obala", "Ora",
    "Ijite", "Ofu", "Atunakpa", "Ululu"
]

# Define word combinations and their meanings
word_combinations = {
    ("Agali", "Agali"): "Ikenga / RIGHT HAND / KNIFE",
    ("Agali", "Akwu"): "Okuku / Ite / CALABASH, EARTHEN POT",
    ("Agali", "Aka"): "Nwaoke / MALE CHILD",
    ("Agali", "Ete"): "Onye Obo / REVENGEFUL PERSON",
    ("Agali", "Ijite"): "Ife kpado Igwe / SOMETHING HANDCUFFED / TO RESTRAIN",
    ("Agali", "Obala"): "Onye di ocha /SOMEONE LIGHT IN COLOUR",
    ("Agali", "Obi"): "Ukwu,Irere / legs/ TO BE Watchful",
    ("Agali", "Ofu"): "EGO / MONEY",
    ("Agali", "Ogoli"): "WATEKILI / CHILD",
    ("Agali", "Okala"): "ONYE ECHICHI / TITLED PERSON",
    ("Agali", "Ora"): "Nseka / TROUBLE AND CONFLICT",
    ("Agali", "Ose"): "Ifele, Mkpi / SHAMEFUL / HE-GOAT",
    ("Agali", "Otule"): "Uzu Onu / BAD MOUTH",
    ("Agali", "Atunakpa"): "Ife a na ewero isi / WORTHLESS / NOTHING",
    ("Agali", "Oddi"): "ILUDO IGWE / SOMETHING HOLDING SOMEONE ONE PLACE",
    ("Agali", "Ululu"): "Ife Ajulu Aju / REJECTED THING",
    ("Aka", "Aka"): "Oso / TO RUN",
    ("Aka", "Akwu"): "Ndi ichie / ANCESTORS",
    ("Aka", "Agali"): "Anu / MEAT / BLOOD SACRIFICE",
    ("Aka", "Ete"): "Alusi nwe mmiri / FEMALE NGENE DEITY",
    ("Aka", "Ijite"): "Ana Obi / EARTH FORCE OF OBI",
    ("Aka", "Obala"): "Ajani / EARTH FORCE",
    ("Aka", "Obi"): "Ekugo / IT IS SAID / DECIDED",
    ("Aka", "Ofu"): "Chi / CREATIVE FORCE",
    ("Aka", "Ogoli"): "Ndi Ekwensu /EVIL PERSON OR SPIRIT",
    ("Aka", "Okala"): "Oya / Illness",
    ("Aka", "Ora"): "Chi / CREATIVE FORCE",
    ("Aka", "Ose"): "Ngwu / NGWU DEITY",
    ("Aka", "Otule"): "Ofo / STAFF OF AUTHORITY / POWER",
    ("Aka", "Atunakpa"): "Osisi Oji / Iroko",
    ("Aka", "Oddi"): "Ajani / EARTH FORCE",
    ("Aka", "Ululu"): "Ndi ichie/ ANCESTORS",
    ("Ete", "Ete"): "IBIDE / SUDDEN / ACCIDENT",
    ("Ete", "Aka"): "IFE GBO / ANCIENT",
    ("Ete", "Akwu"): "NNEKWU / BIG",
    ("Ete", "Agali"): "I OBO / REVENGEFUL AND UNCOMPROMISING",
    ("Ete", "Ijite"): "AkwuKWA / THREE LEGGED OVEN",
    ("Ete", "Obala"): "EZIOKWU / SOMETHING CLEAR",
    ("Ete", "Obi"): "MMILI / WATER BODY",
    ("Ete", "Ofu"): "ODIGO MMA / IT IS SETTLED, ALRIGHT",
    ("Ete", "Ogoli"): "ILADI, ORU NWANYI / ADULTERY",
    ("Ete", "Okala"): "NWANWANYI / FEMALE CHILD",
    ("Ete", "Ora"): "IGBA AMA / TO WARN",
    ("Ete", "Ose"): "ANWUGO IYI / IT HAS BEEN SWORN",
    ("Ete", "Otule"): "OJI / KOLANUT",
    ("Ete", "Atunakpa"): "NWANWANYI / FEMALE CHILD",
    ("Ete", "Oddi"): "IMECHI UZO, ANYASI / CLOSING DOOR/WAY, NIGHT",
    ("Ete", "Ululu"): "AJADU NWANYI / WIDOW",
    ("Akwu", "Akwu"): "AJO ONODU / BAD CONDITION",
    ("Akwu", "Aka"): "EBUNU, NWANKWO / RAM / BORN OF NKWO DAY",
    ("Akwu", "Agali"): "ANU / MEAT / BLOOD SACRIFICE",
    ("Akwu", "Ete"): "ONYE UKWU / BIG MAN / IMPORTANT PERSON",
    ("Akwu", "Ijite"): "EZI NA UNO / COMPOUND",
    ("Akwu", "Obala"): "OGBU EFI / COW",
    ("Akwu", "Obi"): "EWU / GOAT",
    ("Akwu", "Ofu"): "CHI / PROCREATIVE FORCE",
    ("Akwu", "Ogoli"): "IRA UNO / TO ABANDON HOME",
    ("Akwu", "Okala"): "Obi / ANCESTRAL HOUSE",
    ("Akwu", "Ora"): "UNO / HOUSE",
    ("Akwu", "Ose"): "I JI UCHE / AMBUSH / GETTING READY TO HARM",
    ("Akwu", "Otule"): "IKWE EKWE / TO ANNOUNCE",
    ("Akwu", "Atunakpa"): "OBI UKWU / BIG MAN",
    ("Akwu", "Oddi"): "ONUNU, ANA / BIG HOLE / GRAVE",
    ("Akwu", "Ululu"): "Ndi ichie / ANCESTORS",
    ("Ijite", "Ijite"): "IFE KWU NEZI / SOMETHING STANDING OUTSIDE",
    ("Ijite", "Aka"): "IWENI AKA NDU ENU / FREEDOM",
    ("Ijite", "Akwu"): "AKWALI / ITE AWELE / FERTILITY DEITY / AWELE",
    ("Ijite", "Agali"): "ANU KA AGE ME / BLOOD SACRIFICE",
    ("Ijite", "Ete"): "ALUSI MMILI / MKPUME / MALE NGENE DEITY",
    ("Ijite", "Obala"): "NZU / WHITE CHALK",
    ("Ijite", "Obi"): "IZO SI UKWU IKE / STAND FIRMLY ON THE GROUND",
    ("Ijite", "Ofu"): "CHI KELU MMADU / CHI THE CREATOR",
    ("Ijite", "Ogoli"): "NKITI / IFE NKITI / NOTHINGNESS VAIN",
    ("Ijite", "Okala"): "UWKU SI IKE NANI / YOU STAND FIRMLY",
    ("Ijite", "Ora"): "CHI MMADU / CHI OF A PERSON",
    ("Ijite", "Ose"): "ALUSI BU UDO / UDO DEITY",
    ("Ijite", "Otule"): "ANWULI DIA / THERE IS HAPPINESS",
    ("Ijite", "Atunakpa"): "IJEDI MMA / A HAPPY ADVENTURE",
    ("Ijite", "Oddi"): "IFE AGUCHIBIDO / BEHIND CLOSED DOORS",
    ("Ijite", "Ululu"): "IKWU UCHU/ MOURNING /SORROW /TEARS",
    ("Ofu", "ofu"): "IBU AFUFU / TO SUFFER",
    ("Ofu", "Aka"): "IGBANARIGO / YOU HAVE ESCAPED / TO ESCAPE",
    ("Ofu", "Akwu"): "AROBINAGU / AROBINAGU DEITY",
    ("Ofu", "Agali"): "IFE AGA FE MME / BLOOD SACRIFICE",
    ("Ofu", "Ijite"): "OKWU NI NWERO ISI / WORTHLESS TALK",
    ("Ofu", "Ete"): "URU / SORROW, GRIEF",
    ("Ofu", "Obala"): "MMANYA /ALCHOLIC DRINKS",
    ("Ofu", "Obi"): "AJO IJE / BAD JOURNEY / UNSUCCESSFULL",
    ("Ofu", "Ogoli"): "OSEAKA /WORTHLESS & TROUBLESOME PERSON",
    ("Ofu", "Okala"): "NKWU OJUKWU / OJUKWU DEITY",
    ("Ofu", "Ora"): "NDU / ANYANWU NA AGBALA / LIFE ",
    ("Ofu", "Ose"): "ILI NSI / TO EAT POISON",
    ("Ofu", "Otule"): "AFUFU DIA / SUFFERING IS THERE",
    ("Ofu", "Atunakpa"): "ILITE IFE OMA / GAINING GOOD THINGS",
    ("Ofu", "Oddi"): "ALU EME / ABOMINATION OCCURED",
    ("Ofu", "Ululu"): "IGBANARIGO / IWUCHA / YOU HAVE ESCAPED / ITS NOW GOOD",
    ("Obala", "Obala"): "IFE PUTALI IFE / SOMETHING OPEN",
    ("Obala", "Aka"): "IFE AGA EME N'IHU / SOMETHING ABOUT TO COME / FUTURE EVENT",
    ("Obala", "Akwu"): "OGA BU AGHA / COMING WITH WAR OR WITH TROUBLE",
    ("Obala", "Agali"): "IFE AGA JI MMA GBU/ BLOOD SACRIFICE",
    ("Obala", "Ijite"): "DIBIA / AGWU /TRADITIONAL DOCTOR / AGWU FORCE",
    ("Obala", "Ete"): "IFE MME / BLOODY SACRIFICE",
    ("Obala", "Ofu"): "MMANYA / ALCHOLIC DRINKS",
    ("Obala", "Obi"): "OGA MELILI / MUST HAPPEN",
    ("Obala", "Ogoli"): "ECHINA NTI / DONT TURN DEAF EARS / LISTEN",
    ("Obala", "Okala"): "AWUWO CROOKS",
    ("Obala", "Ora"): "OGWU / JUJU",
    ("Obala", "Ose"): "OGWU AGWO / JUJU THAT WAS MADE",
    ("Obala", "Otule"): "DIBIA / TRADITIONAL DOCTOR",
    ("Obala", "Atunakpa"): "ONYE IWE / ANGER / SCOLDING",
    ("Obala", "Oddi"): "ICHENTI / MBA / DEAF EARS / SCOLDING",
    ("Obala", "Ululu"): "OGWA KWAPU IFE OJO ON ELO / PUT ASIDE THE EVIL HE IS THINKING",
    ("Obi", "Obi"): "IGBA EZI / TO REAPPEAR / TWICE",
    ("Obi", "Aka"): "IJE / TO GO",
    ("Obi", "Akwu"): "ORA / GATHERING OF PEOPLE/ POPULACE",
    ("Obi", "Agali"): "ANA ERERE / THEY ARE WALKING ON TIP TOES, TO BE CAREFUL",
    ("Obi", "Ijite"): "IFE IDI MMADU N'AKUKU / SOMETHING BESIDE ONE, BOUNDARY",
    ("Obi", "Ete"): "OKUKO / CHICKEN",
    ("Obi", "Ofu"): "IGBA MBO, STRUGGLING",
    ("Obi", "Obala"): "OGA DI MMA / WILL BE WELL, TO BE WELL",
    ("Obi", "Ogoli"): "ILADI / UBULU / TO HAVE SEX / A CHICK",
    ("Obi", "Okala"): "OBIA JE BEM/ VISITORS COMING TO ME",
    ("Obi", "Ora"): "IFE A RAPULU ARAPU / ABANDONED",
    ("Obi", "Ose"): "IFE DI NSO / SOMETHING NEAR",
    ("Obi", "Otule"): "OKWU GA SUDO / TALKS WILL END WELL CONCLUDED",
    ("Obi", "Atunakpa"): "NDOZI IFE / TO FIX THINGS",
    ("Obi", "Oddi"): "ONA BIA / IS COMING",
    ("Obi", "Ululu"): "AKWA / CRYING",
    ("Ogoli", "Ogoli"): "OSEAKA / WORTHLESS, DESTRUCTIVE",
    ("Ogoli", "Aka"): "OZU GA NWU / DEATH WILL OCCUR",
    ("Ogoli", "Akwu"): "ONUNU / TAKING AWAY THINGS AND DENYING",
    ("Ogoli", "Agali"): "NDI AKA EKPE / ILL-LUCK PERSONS",
    ("Ogoli", "Ijite"): "ALUSI BU OGWUGWU / OGWUGWU DEITY",
    ("Ogoli", "Ete"): "OYA AFO / STOMACH ILLNESS",
    ("Ogoli", "Ofu"): "ORIE / ORIE MARKET DAY",
    ("Ogoli", "Obala"): "OZU / CORPES",
    ("Ogoli", "Obi"): "NWANWANYI / FEMALE CHILD OR GIRL",
    ("Ogoli", "Okala"): "NWANYI TULU IME/ WOMEN WITH KIDS",
    ("Ogoli", "Ora"): "INYA OKU / TO WARM FIRE / ILLNESS",
    ("Ogoli", "Ose"): "IFELE / N NYASI / SHAME / NIGHT",
    ("Ogoli", "Otule"): "KO AKIKO / TELL STORY",
    ("Ogoli", "Atunakpa"): "NWANYI/ FEMALE",
    ("Ogoli", "Oddi"): "IGADO AKA N'UKWU",
    ("Ogoli", "Ululu"): "ONYE GA KWA OZU",
    ("Okala", "Okala"): "IFE ANAZO AZO / STRUGGLING",
    ("Okala", "Aka"): "ITA ALU, IFE NAATA ALU / BITTING",
    ("Okala", "Akwu"): "IFE IKE / ACCIDENT",
    ("Okala", "Agali"): "ANU / MEAT",
    ("Okala", "Ijite"): "AGWU / SPIRIT OF DIVINATION",
    ("Okala", "Ete"): "AKPU / KAPOK TREE",
    ("Okala", "Ofu"): "MMANYA / ALCHOLIC DRINK",
    ("Okala", "Obala"): "AWUWO / BLACKMAIL / TRICKS",
    ("Okala", "Obi"): "OKWUGO / HAS SAID / DECIDED",
    ("Okala", "Ogoli"): "NDI OKALA OGOLI / WORTHLESS PEOPLE",
    ("Okala", "Ora"): "OGWU / CHARM",
    ("Okala", "Ose"): "NGWU, OGWU, NSI/ DEITY / JUJU/ POISON",
    ("Okala", "Otule"): "EZIGBO OKWU / TRUTH",
    ("Okala", "Atunakpa"): "AWUWO / BLACKMAIL / TRICKS",
    ("Okala", "Oddi"): "ISU UDE / GROAN",
    ("Okala", "Ululu"): "IKWA NJO / TO REMOVE EVIL",
    ("Ose", "Ose"): "ANYA / TO SEE",
    ("Ose", "Aka"): "IMEYELI / TO ACT ABNORMALLY",
    ("Ose", "Akwu"): "ZUALI FA AFIA / GO TO MARKET FOR THEM",
    ("Ose", "Agali"): "IHE DI OCHA / TO COME OUT CLEAN",
    ("Ose", "Ijite"): "EJIYI EJI / TO BE HELD",
    ("Ose", "Ete"): "SIA LUFA NNI / COOK FOR THEM",
    ("Ose", "Ofu"): "AMOSU, ORI / THEFT, WITCHCRAFT",
    ("Ose", "Obala"): "NZU / SYMBOL OF PURITY",
    ("Ose", "Obi"): "ZUA AFIA / GO TO MARKET FOR THEM AND OFFER THINGS IN SACRIFICE",
    ("Ose", "Ogoli"): "IYI. IFE MEBILI EMEBI / SPOILT",
    ("Ose", "Ora"): "UCHE, ICHE ECHICHE / THINKING/ THOUGHT",
    ("Ose", "Okala"): "BU NWUCHA, IDI OCHA / CLEANSING",
    ("Ose", "Otule"): "ANWULI / HAPPINESS",
    ("Ose", "Atunakpa"): "ANWULI / HAPPINESS",
    ("Ose", "Oddi"): "IWE / ANGER",
    ("Ose", "Ululu"): "IZE NDU",
    ("Ora", "Ora"): "EKE, OKU / EKE DAY / LIGHT",
    ("Ora", "Aka"): "JE RANRA / GO AND PAY FOR THE FINE",
    ("Ora", "Akwu"): "IFE NSO / A TABOO",
    ("Ora", "Agali"): "UMUNNA / KINDRED",
    ("Ora", "Ijite"): "NDI ICHIE UMUNNA / ANCESTORS LINEAGE",
    ("Ora", "Ete"): "ANYA MMILI / TEARS / WEEPING",
    ("Ora", "Ofu"): "NWANNE / RELATIONS THROUGH MOTHER",
    ("Ora", "Obala"): "EKWENSU / EVIL FORCE",
    ("Ora", "Obi"): "NWANNE / RELATIONS THROUGH MOTHER",
    ("Ora", "Ogoli"): "WATAKILI / A CHILD",
    ("Ora", "Ose"): "OYA / ILLNESS",
    ("Ora", "Okala"): "NWOKE / A MALE CHILD",
    ("Ora", "Otule"): "NWA OKPALA / FIRST MALE SON",
    ("Ora", "Atunakpa"): "NWADA / FIRST DAUGHTER",
    ("Ora", "Oddi"): "ICHENTI, NTI / EAR, DEAF",
    ("Ora", "Ululu"): "NDI IKWUNNE / MATERNAL LINEAGE",
    ("Otule", "Otule"): "IKPE / CASE / TROUBLE",
    ("Otule", "Aka"): "MKPU, ALU EME/ A SHOUT OF ABOMINATION",
    ("Otule", "Akwu"): "ONA FIO UZU / GENERATING COMMOTION",
    ("Otule", "Agali"): "ANWUGO IYI / OATH HAS BEEN SWORN",
    ("Otule", "Ijite"): "OKPA KWALAKWA / COCK",
    ("Otule", "Ete"): "UTA / ARROW",
    ("Otule", "Ofu"): "KA IKPE UDO / NEGOTIATING FOR PEACE",
    ("Otule", "Obala"): "IKPE ILE OMA / PEACEFUL TALK",
    ("Otule", "Obi"): "BIKO KA ONA EKPE / PLEADING",
    ("Otule", "Ogoli"): "ONYE NSOKWU / FOOLISH PERSON",
    ("Otule", "Ose"): "AJO ONU / BAD MOUTH / EVIL TALK",
    ("Otule", "Okala"): "IGBU AGBA,IKA IFE / SCHEDULED, AP",
    ("Otule", "Ora"): "NNTI, INU NA NTI / EARS = HEAR",
    ("Otule", "Atunakpa"): "ITA AKA NA ONU/ REGRET/PAINFULLY",
    ("Otule", "Oddi"): "IFE DI NNUKWU, EGBE / SOMETHING BIG",
    ("Otule", "Ululu"): "AFO / AFO DAY",
    ("Atunakpa", "Atunakpa"): "IKEDO MMADU /TO HANDCUFF /TROUBLE",
    ("Atunakpa", "Aka"): "IGBAPU OSO / RUNNING FOR ONES LIFE",
    ("Atunakpa", "Akwu"): "UKA, OYIBO / CHURCH / ABROAD",
    ("Atunakpa", "Agali"): "MMADO / TO TIE DOWN FIRMLY/ FIX",
    ("Atunakpa", "Ijite"): "NDI NZE, NDI UKWU / TITLED MEN",
    ("Atunakpa", "Ete"): "UGBO / TRANSPORTATION",
    ("Atunakpa", "Ofu"): "NSEKE / TROUBLE",
    ("Atunakpa", "Obala"): "UDALA / JUICY FRUIT / PEACE",
    ("Atunakpa", "Obi"): "NWU ONWU IKE / PREMATURE DEATH",
    ("Atunakpa", "Ogoli"): "NDI NSEKE / TROUBLESOME PERSONS",
    ("Atunakpa", "Ose"): "OGODO, CLOTHES WORD",
    ("Atunakpa", "Okala"): "UKWU ESIGO IKE NANI/STAND FIRMLY",
    ("Atunakpa", "Ora"): "NSEKE /TROUBLE",
    ("Atunakpa", "Otule"): "NDI MGBILIMGBA / OGBANJE",
    ("Atunakpa", "Oddi"): "IKEDO UDO /TIE WITH ROPE/ TROUBLE",
    ("Atunakpa", "Ululu"): "NDICHIE NO N'OBI/ ANCESTRAL HOME",
    ("Ululu", "Ululu"): "IKWU UGWO / TO PAY A DEBT",
    ("Ululu", "Aka"): "NNI / FOOD",
    ("Ululu", "Akwu"): "NNI / FOOD",
    ("Ululu", "Agali"): "ANU MEAT /FLESH",
    ("Ululu", "Ijite"): "JI, IKE OBI/ YAM /STRONG MINDEDNESS",
    ("Ululu", "Ete"): "EDE, AKWA / COCOA YAM / CRY",
    ("Ululu", "Ofu"): "NNI /FOOD",
    ("Ululu", "Obala"): "NNI / FOOD",
    ("Ululu", "Obi"): "NNI / FOOD",
    ("Ululu", "Ogoli"): "AJO NNI / BAD FOOD / POISONED",
    ("Ululu", "Ose"): "AJO NNI, AKPILI / BAD FOOD / THROAT",
    ("Ululu", "Okala"): "NNI / FOOD",
    ("Ululu", "Ora"): "AGU / HUNGER",
    ("Ululu", "Otule"): "NNI / FOOD",
    ("Ululu", "Oddi"): "AJO NNI / BAD FOOD",
    ("Ululu", "Atunakpa"): "NNI / FOOD",
    ("Oddi", "Oddi"): "NDEELI, ABANI / DARKNESS / SUFFERING",
    ("Oddi", "Aka"): "IBU / LOAD /HEAVY TROUBLE",
    ("Oddi", "Akwu"): "IWE NA EWE / THERE IS ANGER DONT LET",
    ("Oddi", "Agali"): "UGBA DAKWASI/ MISFORTUNE FALLS ON ME",
    ("Oddi", "Ijite"): "AJANI / EARTH FORCE",
    ("Oddi", "Ete"): "ODI EGWU  / DANGEROUS AND FEARFUL",
    ("Oddi", "Ofu"): "NNEMU, AFO IME / MOTHER / PREGANCY",
    ("Oddi", "Obala"): "NNENNA, NNEMOCHE / FATHER'S MOTHER",
    ("Oddi", "Obi"): "O DO GO / PEACE HAS BEEN RESTORED",
    ("Oddi", "Ogoli"): "ALUSI BU OGWUGWU / OGWUGWU DEITY",
    ("Oddi", "Ose"): "INO NENU OKWUTE, DIFFICULTIES / ANGRY",
    ("Oddi", "Okala"): "UKWU SI IKE NANI / STAND FIRMLY",
    ("Oddi", "Ora"): "IKU UME NDU / TO BREATH",
    ("Oddi", "Otule"): "NNA, NDINNA /FATHER FATHER'S LINEAGE",
    ("Oddi", "Ululu"): "NDI IKWU NNE / MATHER'S LINEAGE",
    ("Oddi", "Atunakpa"): "NNAMOCHE, FATHER'S MOTHER LINEAGE",
    
}

# Generate a sentence with 4 randomly selected words
sentence = ' '.join(random.choices(words, k=4)) + '.' 
selected_words = sentence[:-1].split()  # Remove the trailing period

print("Generated Sentence:", sentence)
print("\nAFA UGILI TOSSED:")

# Collect all pairs for checking against the dictionary
selected_words_pairs = []

# First group: i < j combinations
for i in range(len(selected_words)):
    for j in range(i + 1, len(selected_words)):
        pair = (selected_words[i], selected_words[j])
        selected_words_pairs.append(pair)
        print(f"{selected_words[i]} + {selected_words[j]}")

# Second group: Reverse pairs starting from the last word
for i in reversed(range(len(selected_words))):
    for j in reversed(range(i)):
        pair = (selected_words[i], selected_words[j])
        selected_words_pairs.append(pair)
        print(f"{selected_words[i]} + {selected_words[j]}")

# Check pairs against the dictionary and print combined meanings
print("\nAFA UGILI INTERPRETATION:")
for pair in selected_words_pairs:
    if pair in word_combinations:
        print(f"{pair[0]} + {pair[1]} = {word_combinations[pair]}")
    else:
        print(f"{pair[0]} + {pair[1]} = No known meaning")