name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  # Updated to LTS version

    steps:
      - uses: actions/checkout@v4  # Updated to latest version

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Buildozer Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev git unzip openjdk-17-jdk
          pip3 install --user buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT

      - name: Cache Buildozer Global Directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer Directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Accept Android Licenses
        run: |
          yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-package
          path: ${{ steps.buildozer.outputs.filename }}
